[project]
name = "connect-python-noextras"
version = "0.1.0"
dependencies = [
  "connect-python",
  "connect-python-example",
  "pytest==9.0.1",
  "pytest-asyncio==1.3.0",
  "pytest-cov==7.0.0",
]

[tool.ruff]
extend = "../pyproject.toml"
