[project]
name = "connect-python-noextras"
version = "0.1.0"
dependencies = [
  "connect-python",
  "connect-python-example",

  # Versions locked in constraint-dependencies
  "pytest",
  "pytest-asyncio",
  "pytest-cov",
  "pytest-timeout",
]

[tool.ruff]
extend = "../pyproject.toml"
